### ISSUE TITLE
gift-copr fedora 35 builld issues python 3.10 icw pyparsing 3.0.5

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#1055]
```
Traceback (most recent call last):
  File "/usr/lib/rpm/pythondistdeps.py", line 564, in <module>
    raise RuntimeError("Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.") from exc
RuntimeError: Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.
error: Dependency tokens must begin with alpha-numeric, '_' or '/': *** PYTHONDISTDEPS_GENERATORS_FAILED ***
Traceback (most recent call last):
  File "/usr/lib/rpm/pythondistdeps.py", line 561, in <module>
    main()
  File "/usr/lib/rpm/pythondistdeps.py", line 372, in main
    dist = Distribution(f)
  File "/usr/lib/rpm/pythondistdeps.py", line 86, in __init__
    self.requirements = [Requirement(r) for r in self.requires or []]
  File "/usr/lib/rpm/pythondistdeps.py", line 86, in <listcomp>
    self.requirements = [Requirement(r) for r in self.requires or []]
  File "/usr/lib/rpm/pythondistdeps.py", line 68, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 1100, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 4024, in parseImpl
    return e._parse(
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 4854, in parseImpl
    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 827, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 283, in wrapper
    ret = func(*args[limit:])
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 71, in <lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by joachimmetz** [comment]
Looks like a conflict between pyparsing 3.0.5 and packaging
