### ISSUE TITLE
l2tbinaries address No module named 'packaging' for redis 4.1.0 or later

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#1063]
```
python.exe : Traceback (most recent call last):
At line:1 char:1
+ & 'C:\Python310\python.exe' C:\Python310\Scripts\log2timeline.py --no ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Python310\Scripts\log2timeline.py", line 11, in <module>
    from plaso.cli import log2timeline_tool
  File "C:\Python310\lib\site-packages\plaso\cli\log2timeline_tool.py", line 15, in <module>
    from plaso.cli import extraction_tool
  File "C:\Python310\lib\site-packages\plaso\cli\extraction_tool.py", line 34, in <module>
    from plaso.multi_process import extraction_engine as multi_extraction_engine
  File "C:\Python310\lib\site-packages\plaso\multi_process\extraction_engine.py", line 21, in <module>
    from plaso.multi_process import extraction_process
  File "C:\Python310\lib\site-packages\plaso\multi_process\extraction_process.py", line 14, in <module>
    from plaso.multi_process import task_process
  File "C:\Python310\lib\site-packages\plaso\multi_process\task_process.py", line 6, in <module>
    import redis
  File "C:\Python310\lib\site-packages\redis\__init__.py", line 8, in <module>
    from redis.client import Redis, StrictRedis
  File "C:\Python310\lib\site-packages\redis\client.py", line 15, in <module>
    from redis.connection import ConnectionPool, SSLConnection, UnixDomainSocketConnection
  File "C:\Python310\lib\site-packages\redis\connection.py", line 13, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by joachimmetz** [comment]
also new dependency on python3-importlib-metadata ?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/1091

**Comment by joachimmetz** [comment]
```
ModuleNotFoundError: No module named 'typing_extensions'
```

And typing_extensions requires flit (since it uses toml)
