### ISSUE TITLE
review script: issue after create

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#211]
Most likely related to https://github.com/log2timeline/l2tdevtools/issues/209, but this time the CR is created, and I have a different traceback.

```
Traceback (most recent call last):
  File "utils/review.py", line 2246, in <module>
    if not Main():
  File "utils/review.py", line 2219, in Main
    result = review_helper.Create()
  File "utils/review.py", line 1676, in Create
    self._project_name, self._diffbase, code_review_description)
  File "utils/review.py", line 300, in CreateIssue
    exit_code, output, _ = self.RunCommand(command)
  File "utils/review.py", line 61, in RunCommand
    command, error))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1549: ordinal not in range(128)
```

**Comment by joachimmetz** [comment]
Create option no longer exists
