### ISSUE TITLE
review: issue on merge

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#231]
issue when merging https://codereview.appspot.com/334220043/

```
Traceback (most recent call last):
  File "l2tdevtools/tools/review.py", line 252, in <module>
    if not Main():
  File "l2tdevtools/tools/review.py", line 234, in Main
    result = review_helper.Merge(codereview_issue_number)
  File "l2tdevtools/l2tdevtools/helpers/review.py", line 394, in Merge
    codereview_issue_number, self._merge_author, self._merge_description):
  File "l2tdevtools/l2tdevtools/helpers/git.py", line 148, in CommitToOriginInNameOf
    exit_code, _, _ = self.RunCommand(command)
  File "l2tdevtools/l2tdevtools/helpers/cli.py", line 38, in RunCommand
    arguments = shlex.split(command)
  File "/usr/lib64/python2.7/shlex.py", line 275, in split
    lex = shlex(s, posix=posix)
  File "/usr/lib64/python2.7/shlex.py", line 25, in __init__
    instream = StringIO(instream)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 182: ordinal not in range(128)
```

**Comment by Onager** [comment]
This is due to the long codereview description, reitveld adds a ellipsis unicode character.

I was once told that this was motivation to keep the description short....

**Comment by joachimmetz** [comment]
We probably should try to keep them short. Maybe we should add a check on create to limit the length of the description.

**Comment by joachimmetz** [comment]
we stopped using rietveld, closing issue
