### ISSUE TITLE
fix Python 3 tests on appveyor

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#300]
make changes to have Python 3 tests on appveyor pass

**Comment by joachimmetz** [comment]
Encoding issue with configparser

```
======================================================================
ERROR: testRead (projects.ProjectDefinitionReaderTest)
Tests the Read function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\l2tdevtools\tests\projects.py", line 84, in testRead
    file_object):
  File "C:\projects\l2tdevtools\l2tdevtools\projects.py", line 230, in Read
    config_parser.read_file(file_object)
  File "C:\Python36\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "C:\Python36\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3342: character maps to <undefined>
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/688

**Comment by joachimmetz** [comment]
https://ci.appveyor.com/project/log2timeline/l2tdevtools/builds/24481525
