### ISSUE TITLE
Don't hardcode dates/versions fetched from remote projects in tests

### ISSUE THREAD

**Issue by rgayon** [log2timeline/l2tdevtools#341]
l2tdevtools own tests fail when the versions of projects in tests/download_helpers/github.py or tests/download_helpers/pypi.py have a new version.

Maybe check that you get a proper %Y%M%D value that make sense? (ie: more than 20000101 and less than 30000101 =) )
```
======================================================================
FAIL: testGetLatestVersion (download_helpers.github.Log2TimelineGitHubReleasesDownloadHelperTest)
Tests the GetLatestVersion functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dev/l2tdevtools/tests/download_helpers/github.py", line 128, in testGetLatestVersion
    self.assertEqual(latest_version, self._PROJECT_VERSION)
AssertionError: u'20180507' != u'20180418'
- 20180507
+ 20180418


======================================================================
FAIL: testGetLatestVersion (download_helpers.pypi.PyPIDownloadHelperTest)
Tests the GetLatestVersion functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dev/l2tdevtools/tests/download_helpers/pypi.py", line 32, in testGetLatestVersion
    self.assertEqual(latest_version, self._PROJECT_VERSION)
AssertionError: u'20180507' != u'20180418'
- 20180507
+ 20180418


----------------------------------------------------------------------
Ran 77 tests in 31.924s
```

**Comment by joachimmetz** [comment]
@rgayon this is working as intended.
