### ISSUE TITLE
build script: version issue when building libewf

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#413]
```
Traceback (most recent call last):
  File "./tools/build.py", line 354, in <module>
    if not Main():
  File "./tools/build.py", line 332, in Main
    if not project_builder.Build(project_definition):
  File "./tools/build.py", line 180, in Build
    return self._BuildProject(download_helper_object, project_definition)
  File "./tools/build.py", line 62, in _BuildProject
    source_helper_object.Clean()
  File "l2tdevtools/l2tdevtools/source_helper.py", line 263, in Clean
    project_version = self.GetProjectVersion()
  File "l2tdevtools/l2tdevtools/source_helper.py", line 359, in GetProjectVersion
    self.project_name, version_definition)
  File "l2tdevtools/l2tdevtools/download_helpers/github.py", line 157, in GetLatestVersion
    latest_match = list(comparable_matches.values()).index(latest_match)
ValueError: None is not in list
```

**Comment by joachimmetz** [comment]
Fix implemented in https://github.com/log2timeline/l2tdevtools/commit/6757c3bdef8b06cc9d5983d87d7e6c47e9570efc
