### ISSUE TITLE
Issue with update-dependencies.py when updating artifacts

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#432]
```
Traceback (most recent call last):
  File "l2tdevtools/tools/update-dependencies.py", line 86, in <module>
    if not Main():
  File "l2tdevtools/tools/update-dependencies.py", line 40, in Main
    project_definition = projects_helper.ReadDefinitionFile()
AttributeError: 'ProjectHelper' object has no attribute 'ReadDefinitionFile'
```

**Comment by joachimmetz** [comment]
Seems to have been resolved
