### ISSUE TITLE
Fix failing pylint CI test

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#473]
Pylint CI test is failing.

https://travis-ci.org/log2timeline/l2tdevtools/jobs/450087377

It appears latest version of astroid has new dependencies.
```
    'typing;python_version<"3.5"',
    'typed_ast;python_version<"3.7" and implementation_name== "cpython"',
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/474

**Comment by joachimmetz** [comment]
Pending new build astroid and typing on GIFT PPA

**Comment by joachimmetz** [comment]
With typing:
```
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==1.7.5', 'console_scripts', 'pylint')()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 12, in run_pylint
    from pylint.lint import Run
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 43, in <module>
    import astroid
  File "/usr/lib/python2.7/dist-packages/astroid/__init__.py", line 59, in <module>
    from astroid.exceptions import *
  File "/usr/lib/python2.7/dist-packages/astroid/exceptions.py", line 13, in <module>
    from astroid import util
  File "/usr/lib/python2.7/dist-packages/astroid/util.py", line 148
    yield from islice(iterator, size)
             ^
SyntaxError: invalid syntax
```

New astroid seems to require python 3.4

**Comment by joachimmetz** [comment]
Reverting back to 1.6.2 for now

**Comment by joachimmetz** [comment]
TODO for migration create separate dev-python2 PPA for legacy packages

**Comment by joachimmetz** [comment]
Also see: https://github.com/log2timeline/l2tdevtools/issues/359
