### ISSUE TITLE
investigate failing pefile import

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#476]
Pefile failing to import on AppVeyor (https://ci.appveyor.com/project/Log2timeline/plaso/builds/20048108/job/y2y84nyebn7744me)

Seen similar issue on FC29 due to python-future

And unclear error on Travis-CI (https://travis-ci.org/log2timeline/plaso/jobs/450715492)

**Comment by joachimmetz** [comment]
dateutil appears to be failing for Linux

```
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/root/.jenkins-slave/workspace/plaso-linux-e2e-acserver/plaso/cli/log2timeline_tool.py", line 16, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "/root/.jenkins-slave/workspace/plaso-linux-e2e-acserver/plaso/output/__init__.py", line 4, in <module>
    from plaso.output import dynamic
  File "/root/.jenkins-slave/workspace/plaso-linux-e2e-acserver/plaso/output/dynamic.py", line 10, in <module>
    from plaso.lib import timelib
  File "/root/.jenkins-slave/workspace/plaso-linux-e2e-acserver/plaso/lib/timelib.py", line 19, in <module>
    import dateutil.parser
ImportError: No module named parser
```

**Comment by joachimmetz** [comment]
Unfortunately pypi has a maintenance window https://status.python.org/

**Comment by joachimmetz** [comment]
Fix for dateutil https://github.com/log2timeline/l2tdevtools/pull/482

**Comment by joachimmetz** [comment]
With GIFT PPA update and pyparsing fixes in plaso Linux and MacOS tests are passing again
https://travis-ci.org/log2timeline/plaso/builds/453537329

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pefile.py", line 23, in <module>
    from builtins import bytes
ImportError: No module named builtins
```

I've not been able to reproduce this locally

**Comment by joachimmetz** [comment]
Create https://github.com/log2timeline/plaso/pull/2199 to test

fresh built of future seems to have solved the issue

**Comment by joachimmetz** [comment]
AppVeyor tests pass again: https://ci.appveyor.com/project/Log2timeline/plaso/builds/20224555

Remaining is to get the changes merged and clean up testing PRs
