### ISSUE TITLE
Add xenial tests to travis configuration

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#515]
Travis now seems to support xenial (besides trusty and precise):

* https://docs.travis-ci.com/user/reference/xenial/
* https://docs.travis-ci.com/user/reference/trusty/
* https://docs.travis-ci.com/user/reference/precise/

To do:

* [x] ~~make changes to add xenial support~~
  * ~~https://github.com/log2timeline/l2tdevtools/pull/516~~
* [x] ~~migrate individual projects to use xenial~~
* [x] Pending changes https://github.com/log2timeline/l2tdevtools/pull/560
  * ~~make changes to have pylint run on xenial - https://github.com/log2timeline/l2tdevtools/issues/359~~
  * ~~make changes to remove trusty support~~

**Comment by joachimmetz** [comment]
`coverage` was rename to `python-coverage` on xenial
https://packages.ubuntu.com/xenial/amd64/python-coverage/filelist

**Comment by joachimmetz** [comment]
Travis and tox https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script

**Comment by joachimmetz** [comment]
```
60.01s$ ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
Traceback (most recent call last):
  File "/usr/bin/pylint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34>=1.1.3' distribution was not found and is required by astroid
The command "./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh" exited with 1
```
