### ISSUE TITLE
Make update-dependencies.py Python3 compatible

### ISSUE THREAD

**Issue by alimez** [log2timeline/l2tdevtools#611]
When trying to run tools/update-dependencies.py using python3 program errors because of string format in python3.

`Traceback (most recent call last):
  File "../l2tdevtools/tools/update-dependencies.py", line 103, in <module>
    if not Main():
  File "../l2tdevtools/tools/update-dependencies.py", line 64, in Main
    writer.Write()
  File "USERNAME/plaso/l2tdevtools/l2tdevtools/dependency_writers/appveyor_yml.py", line 63, in Write
    template_data = self._GenerateFromTemplate('environment', template_mappings)
  File "/USERNAME/plaso/l2tdevtools/l2tdevtools/dependency_writers/appveyor_yml.py", line 37, in _GenerateFromTemplate
    template_filename, template_mappings)
  File "/USERNAME/plaso/l2tdevtools/l2tdevtools/dependency_writers/interface.py", line 51, in _GenerateFromTemplate
    return template_string.substitute(template_mappings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/string.py", line 130, in substitute
    return self.pattern.sub(convert, self.template)
TypeError: cannot use a string pattern on a bytes-like object
`

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/689
