### ISSUE TITLE
Fix issues with installroot

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#633]
Sometimes installroot gives issues, detect if it exists before removing.

```
Traceback (most recent call last):
  File "./tools/build.py", line 474, in <module>
    if not Main():
  File "./tools/build.py", line 431, in Main
    if not project_builder.Build(project_definition):
  File "./tools/build.py", line 122, in Build
    build_helper_object, source_helper_object, distribution):
  File "./tools/build.py", line 70, in _BuildProject
    if not build_required or build_helper_object.Build(source_helper_object):
  File "/home/test/Projects/l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 1007, in Build
    source_helper_object, source_directory, project_version):
  File "/home/test/Projects/l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 234, in _CreatePackagingFiles
    build_configuration = self._DetermineBuildConfiguration(source_directory)  # pylint: disable=assignment-from-none
  File "/home/test/Projects/l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 778, in _DetermineBuildConfiguration
    shutil.rmtree(os.path.join(source_directory, 'installroot'))
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: 'pandas-0.24.2/installroot'
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/634
