### ISSUE TITLE
Remove dependency on xenial

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#650]
Travis CI image is currently on Xenial. However Xenial has numerous outdated dependencies. Move Travis CI tests to Docker Bionic (pylint, coverage) to remove dependency on Xenial.

* [x] remove l2tbinary tests
* [x] move pylint tests
  * test with dfDateTime https://github.com/log2timeline/dfdatetime/pull/140
  * changes to l2tdevtools https://github.com/log2timeline/l2tdevtools/pull/652
  * changed dfwinreg, dfdvfs, plaso
  * timesketch not depended on xenial GIFT PPA packages
* [x] move coverage tests
  * test with dfDateTime https://github.com/log2timeline/dfdatetime/pull/142
  * changes to l2tdevtools https://github.com/log2timeline/l2tdevtools/pull/668
    * ~~clean up: remove linux target from install.sh~~
  * pending changes to dfwinreg, dfdvfs, plaso
* [x] remove xenial from the default build distributions https://github.com/log2timeline/l2tdevtools/pull/671
* [x] move jenkins tests
  * depends on https://github.com/log2timeline/l2tdevtools/issues/667
  * changes to l2tdevtools https://github.com/log2timeline/l2tdevtools/pull/672
* [x] migrate end-to-end test runners to bionic
* [x] remove xenial packages from GIFT PPA testing
* [x] remove xenial packages from GIFT PPA dev
* [x] remove xenial packages from GIFT PPA pylint3
* [ ] remove xenial packages from GIFT PPA stable - moved to https://github.com/log2timeline/l2tdevtools/issues/706

**Comment by joachimmetz** [comment]
Also address:
* https://github.com/google/timesketch/pull/856
* https://travis-ci.org/google/timesketch/jobs/510822043

**Comment by joachimmetz** [comment]
```
60.01s$ ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.2.2', 'console_scripts', 'pylint')()
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 17, in run_pylint
    from pylint.lint import Run
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 76, in <module>
    import astroid
  File "/usr/lib/python3/dist-packages/astroid/__init__.py", line 63, in <module>
    from astroid.nodes import *
  File "/usr/lib/python3/dist-packages/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 38, in <module>
    from astroid import bases
  File "/usr/lib/python3/dist-packages/astroid/bases.py", line 33, in <module>
    MANAGER = manager.AstroidManager()
  File "/usr/lib/python3/dist-packages/astroid/util.py", line 26, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/astroid/manager.py", line 25, in <module>
    from astroid import modutils
  File "/usr/lib/python3/dist-packages/astroid/modutils.py", line 35, in <module>
    from distutils.sysconfig import get_python_lib  # pylint: disable=import-error
ModuleNotFoundError: No module named 'distutils.sysconfig'
```

**Comment by joachimmetz** [comment]
@berggren FYI
