### ISSUE TITLE
pylint: look into additional dependency python3-distutils for astroid

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#700]
look into additional dependency python3-distutils for astroid

**Comment by joachimmetz** [comment]
From https://github.com/log2timeline/l2tdevtools/issues/650

astroid has additional dependency on python3-distutils

```
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.2.2', 'console_scripts', 'pylint')()
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 17, in run_pylint
    from pylint.lint import Run
  File "/usr/lib/python3/dist-packages/pylint/lint.py", line 76, in <module>
    import astroid
  File "/usr/lib/python3/dist-packages/astroid/__init__.py", line 63, in <module>
    from astroid.nodes import *
  File "/usr/lib/python3/dist-packages/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "/usr/lib/python3/dist-packages/astroid/node_classes.py", line 38, in <module>
    from astroid import bases
  File "/usr/lib/python3/dist-packages/astroid/bases.py", line 33, in <module>
    MANAGER = manager.AstroidManager()
  File "/usr/lib/python3/dist-packages/astroid/util.py", line 26, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/astroid/manager.py", line 25, in <module>
    from astroid import modutils
  File "/usr/lib/python3/dist-packages/astroid/modutils.py", line 35, in <module>
    from distutils.sysconfig import get_python_lib  # pylint: disable=import-error
ModuleNotFoundError: No module named 'distutils.sysconfig'
```

**Comment by joachimmetz** [comment]
No longer needed since we don't need to build a recent pylint any more https://github.com/log2timeline/l2tdevtools/issues/838
