### ISSUE TITLE
build.py dpkg fails to find installroot when invoked with python 3

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#746]
`build.py dpkg` fails to find installroot when invoked with python 3

```
Traceback (most recent call last):
  File "./tools/build.py", line 523, in <module>
    if not Main():
  File "./tools/build.py", line 480, in Main
    if not project_builder.Build(project_definition):
  File "./tools/build.py", line 127, in Build
    build_helper_object, source_helper_object, distribution):
  File "./tools/build.py", line 75, in _BuildProject
    if not build_required or build_helper_object.Build(source_helper_object):
  File "l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 872, in Build
    if not self._CreatePackagingFiles(source_directory, project_version):
  File "l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 231, in _CreatePackagingFiles
    build_configuration = self._DetermineBuildConfiguration(source_directory)  # pylint: disable=assignment-from-none
  File "l2tdevtools/l2tdevtools/build_helpers/dpkg.py", line 760, in _DetermineBuildConfiguration
    for directory_entry in os.listdir(dist_packages):
FileNotFoundError: [Errno 2] No such file or directory: 'backports.lzma-0.0.13/installroot/usr/local/lib/python2.7/dist-packages'
```

A directory `backports.lzma-0.0.13/installroot/usr/local/lib/python3.6/dist-packages` exists

**Comment by joachimmetz** [comment]
backports is not needed for Python 3, closing issue
