### ISSUE TITLE
l2tbinaries FC30 docker test fails due missing UTF-8 locale

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#748]
```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 87, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 67, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 414, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/usr/lib/python2.7/site-packages/plaso/cli/extraction_tool.py", line 218, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/plaso/engine/engine.py", line 279, in PreprocessSources
    operating_system = self._DetermineOperatingSystem(searcher)
  File "/usr/lib/python2.7/site-packages/plaso/engine/engine.py", line 93, in _DetermineOperatingSystem
    for path_spec in searcher.Find(find_specs=find_specs):
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/file_system_searcher.py", line 476, in Find
    for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/file_system_searcher.py", line 450, in _FindInFileEntry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/os_file_entry.py", line 205, in _GetSubFileEntries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/os_file_entry.py", line 47, in _EntriesGenerator
    location, directory_entry])
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/os_file_system.py", line 192, in JoinPath
    segment.split(self.PATH_SEPARATOR) for segment in path_segments]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
The command "./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh" exited with 1.
```

**Comment by joachimmetz** [comment]
Looks like the FC30 docker image used is missing a UTF-8 locale and instead uses `ANSI_X3.4-1968` 

https://travis-ci.org/log2timeline/l2tbinaries/jobs/557685094#L1301

**Comment by joachimmetz** [comment]
https://fedoraproject.org/wiki/Changes/Glibc_locale_subpackaging

**Comment by joachimmetz** [comment]
installed langpack.en and changed LANG to C.utf8, tests are passing again https://travis-ci.org/log2timeline/l2tbinaries/builds/558230670
