### ISSUE TITLE
Latest version of kombu is too new for Ubuntu 18.04

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#826]
```
>>> import timesketch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kombu/utils/compat.py", line 12, in <module>
    from importlib import metadata as importlib_metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/timesketch/__init__.py", line 23, in <module>
    from celery import Celery
  File "/usr/lib/python3/dist-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/lib/python3/dist-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/lib/python3/dist-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/lib/python3/dist-packages/celery/utils/__init__.py", line 9, in <module>
    from kombu.utils.objects import cached_property
  File "/usr/lib/python3/dist-packages/kombu/utils/__init__.py", line 5, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/lib/python3/dist-packages/kombu/utils/compat.py", line 14, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

Which appears to be Python 3.8 native https://pypi.org/project/importlib-metadata/

**Comment by joachimmetz** [comment]
For now kombu has been removed from dev track

**Comment by joachimmetz** [comment]
importlib_metadata and zipp have been added. Closing issue
