### ISSUE TITLE
Plaso Timesketch end-to-end tests failing due missing dependency of latest importlib_metadata

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#963]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kombu/utils/compat.py", line 11, in <module>
    from importlib import metadata as importlib_metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/importlib_metadata/_compat.py", line 8, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tsctl", line 11, in <module>
    load_entry_point('timesketch==20201120', 'console_scripts', 'tsctl')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/dist-packages/timesketch/tsctl.py", line 41, in <module>
    from timesketch.app import create_app
  File "/usr/lib/python3.6/dist-packages/timesketch/app.py", line 25, in <module>
    from celery import Celery
  File "/usr/lib/python3/dist-packages/celery/local.py", line 492, in __getattr__
    [name])
  File "/usr/lib/python3/dist-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/usr/lib/python3/dist-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/lib/python3/dist-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/usr/lib/python3/dist-packages/kombu/utils/__init__.py", line 4, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/lib/python3/dist-packages/kombu/utils/compat.py", line 14, in <module>
    import importlib_metadata
  File "/usr/lib/python3/dist-packages/importlib_metadata/__init__.py", line 15, in <module>
    from ._compat import (
  File "/usr/lib/python3/dist-packages/importlib_metadata/_compat.py", line 15, in <module>
    from typing_extensions import Protocol  # type: ignore
```

**Comment by joachimmetz** [comment]
This is on bionic, will be moving this test to focal instead.

**Comment by joachimmetz** [comment]
```
The following packages have unmet dependencies:
 timesketch-server : Depends: gunicorn3 but it is not installable
                     Recommends: redis-server but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
