### ISSUE TITLE
cffi: change dpkg files to not conflict with Ubuntu 18.04 python3-cffi-backend

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#968]
cffi: change dpkg files to not conflict with Ubuntu 18.04 python3-cffi-backend

**Comment by joachimmetz** [comment]
For now backport the cffi version of latest Ubuntu

**Comment by joachimmetz** [comment]
```
====== 1945 passed, 92 skipped, 4 xfailed, 195 warnings in 964.31 seconds ======
I: pybuild base:217: python3.6 -m pytest c/ testing/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
E: pybuild pybuild:336: test: plugin custom failed with: exit code=1: python3.6 -m pytest c/ testing/
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 3.6 returned exit code 13
```

Disable tests
